version: "3"

services:
  json-server:
    container_name: API
    restart: always
    command: yarn json-server -H ${REACT_APP_API_HOST} --watch db.json --port ${REACT_APP_API_PORT}
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    volumes:
      - ./data:/data
    ports:
      - "3001:3001"

  frontend:
    container_name: frontend
    restart: always
    command: yarn start
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - "../frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    links:
      - json-server
